require('morgan.packer')
require('morgan.settings')
require('morgan.remap')
require('morgan.highlights')
require('morgan.auto-commands')
require('morgan.commands')
require('morgan.statusline')
require('morgan.vimwiki')
